### ISSUE TITLE
Error while building Dockerfile

### ISSUE THREAD

**Issue by Blebesquefee** [ropfuscator/ropfuscator#12]
Hi !
I tried to build the docker image using the given Dockerfile but this one failed to compute cache key.
Here is the give output.
![SCR-20231203-ovyi](https://github.com/ropfuscator/ropfuscator/assets/78823108/2a23b124-5b93-4200-b300-009310c87351)

**Comment by peperunas** [comment]
Hello @Blebesquefee, thank you for your interest in ROPfuscator!

Unfortunately, I forgot to remove the Dockerfile as it is not supported for reproducing the project. Please use the Nix flake instead :-)

**Comment by Blebesquefee** [comment]
Hi @peperunas,
Thanks for your response !
Anyways, I don't have much knowledge about nix flakes ... Is there any other way to build and use your project ?
